### ISSUE TITLE
Undefined Array Key

### ISSUE THREAD

**Issue by john-woodrow** [cosmocode/pagenav#22]
### Issue Description

Using PHP 8, almost random pages using Dokuwiki pagenav plugin Get the following warning:
Warning: Undefined array key 1 in /home/ch2644/public_html/dokusoft/lib/plugins/pagenav/syntax.php on line 42

**Comment by StarArmy** [comment]
I'm seeing the same thing in my logs:

`
2024-07-21 17:11:53E_WARNING: Undefined array key 1/home/username/wiki.stararmy.com/lib/plugins/pagenav/syntax.php(41)
    #0 /home/username/wiki.stararmy.com/lib/plugins/pagenav/syntax.php(41): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/username...', 41)
    #1 /home/username/wiki.stararmy.com/inc/parser/handler.php(298): syntax_plugin_pagenav->handle('<10>', 5, 209, Object(Doku_Handler))
    #2 /home/username/wiki.stararmy.com/inc/Parsing/Lexer/Lexer.php(269): Doku_Handler->plugin('[<10>]', 5, 209, 'pagenav')
    #3 /home/username/wiki.stararmy.com/inc/Parsing/Lexer/Lexer.php(196): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('[<10>]', 5, 209)
    #4 /home/username/wiki.stararmy.com/inc/Parsing/Lexer/Lexer.php(146): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '[<10>]', '_plugin_pagenav', 209, 209)
    #5 /home/username/wiki.stararmy.com/inc/Parsing/Parser.php(113): dokuwiki\Parsing\Lexer\Lexer->parse('\n\n<nspages cale...')
    #6 /home/username/wiki.stararmy.com/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse('\n~~NOCACHE~~\n\n ...')
    #7 /home/username/wiki.stararmy.com/inc/parserutils.php(198): p_get_instructions('~~NOCACHE~~\n\n ...')
    #8 /home/username/wiki.stararmy.com/inc/parserutils.php(520): p_cached_instructions('/home/username...', false, 'calendar:sideba...')
    #9 /home/username/wiki.stararmy.com/inc/parserutils.php(299): p_render_metadata('calendar:sideba...', Array)
    #10 /home/username/wiki.stararmy.com/inc/Cache/CacheRenderer.php(79): p_get_metadata('calendar:sideba...', 'date valid')
    #11 /home/username/wiki.stararmy.com/inc/Cache/Cache.php(79): dokuwiki\Cache\CacheRenderer->addDependencies()
    #12 /home/username/wiki.stararmy.com/inc/parserutils.php(152): dokuwiki\Cache\Cache->useCache()
    #13 /home/username/wiki.stararmy.com/inc/parserutils.php(97): p_cached_output('/home/username...', 'xhtml', 'calendar:sideba...')
    #14 /home/username/wiki.stararmy.com/inc/template.php(1658): p_wiki_xhtml('calendar:sideba...', '', false)
    #15 /home/username/wiki.stararmy.com/lib/tpl/StarArmyGhostNebula2017/main.php(50): tpl_include_page('calendar:sideba...', true, true)
    #16 /home/username/wiki.stararmy.com/inc/actions.php(30): include('/home/username...')
    #17 /home/username/wiki.stararmy.com/doku.php(131): act_dispatch()
    #18 {main}
`

**Comment by gdighton** [comment]
`list($mode, $glob) = explode(' ', $match, 2);`

The issue is that explode() is may return an array with less than two elements - if there's no space (which there usually is not because you aren't using a regular expression argument, then explode returns an array with only a single element (the entire $match string).

The output needs to be checked for length...

Fixed version:

```  
public function handle($match, $state, $pos, Doku_Handler $handler)
    {
        //split the match in it's parts
        $match = substr($match, 1, -1);
		$arr = explode(' ', $match, 2);
		if (count($arr) == 2) {
			list($mode, $glob) = $arr;
		} else {
			$mode = $arr[0];
			$glob = '';
		}
        $mode = (int)substr($mode, 1, -1);
        if (!$mode) $mode = 2 + 4 + 8;

        return array(strtolower(trim($glob)), $mode);
    }
```
